# Generated by Django 4.1 on 2025-04-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_app_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
